### ISSUE TITLE
Add instructions on caching plugin downloads and compiles with github actions

### ISSUE THREAD

**Issue by dsherret** [dprint/dprint#248]
As title.

I believe this is done similar to the following:

```
      - name: Cache dprint plugins
        uses: actions/cache@v1
        if: matrix.config.kind == 'lint'
        with:
          path: ~/.cache/dprint
          key: ${{ matrix.config.os }}-dprint-plugins-${{ hashFiles('**/.dprintrc.json') }}
```

But I'm not sure.
