### ISSUE TITLE
Add github action for dprint

### ISSUE THREAD

**Issue by dsherret** [dprint/dprint#297]
Prior art: https://github.com/axel-op/googlejavaformat-action

Supersedes #248

**Comment by thomaseizinger** [comment]
Couple of thoughts on this:

1. It would be nice to cache the dprint binary based on the version. As such, the action should probably take the version as an input.
2. With the [`@actions/cache`](https://github.com/actions/toolkit/tree/main/packages/cache) package being available, it would be good if the action would automatically set up a cache for all the plugins that are being used.
3. By default, the action should simply verify the formatting. I think that is the most common use-case in CI.

All of this together would allow us to use dprint within GH actions using a single step! I am imagining this as:

```yaml
jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Check formatting
        uses: dprint/check@v2
```
