### ISSUE TITLE
TOML formatter doesn't respect line length

### ISSUE THREAD

**Issue by rminami** [dprint/dprint#932]
Version: 0.47.4

I have a `dprint.jsonc` that looks like this

```
{
  "toml": {
    "lineWidth": 80
  },
  "excludes": [],
  "plugins": ["https://plugins.dprint.dev/toml-0.6.3.wasm"]
}
```

and a Cargo.toml file that looks like this.

```toml
[package]
name = "playground"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8.2", default-features = false, features = ["chrono", "macros", "postgres", "runtime-tokio-rustls", "uuid"] }
```

Given the 80 character line width, I would expect dprint to reformat the `sqlx` line to

```toml
sqlx = { version = "0.8.2", default-features = false, features = [
  "chrono",
  "macros",
  "postgres",
  "runtime-tokio-rustls",
  "uuid",
] }
```

However, it is kept as is. This seems like unintended behavior?
